### ISSUE TITLE
Bayesian Process issues

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jaspProcess#92]
Just tried the Bayesian process analysis, but quickly ran into some issues:
- there is no runjags package
![image](https://github.com/jasp-stats/jaspProcess/assets/15704203/32ebf85c-9afd-41c2-8dbf-efaee786053f)

- dim(x) positive length when Hayes model not fully configured?

see attached jasp file (change ext)
[bayesprocerrors.zip](https://github.com/jasp-stats/jaspProcess/files/15249230/bayesprocerrors.zip)

**Comment by maltelueken** [comment]
I cannot reproduce the first issue... are you using a nightly and which OS are you using?

The second one is a bit more tricky because apparently the `blavaan` does not properly accept the `do.fit` argument and tries to estimate a model even though the model is not complete yet.

**Comment by JohnnyDoorn** [comment]
Yes sorry for not providing all info.. Im on Mac Sonoma, using https://github.com/jasp-stats/jasp-desktop/commit/a2ea390e3d127f56f515b4407dcd5d48d003a74e

**Comment by maltelueken** [comment]
I fixed the second error (was easier than I thought in the end), but I still cannot reproduce the first one. Perhaps the installation of `jaspJags` was interrupted or incomplete. How exactly did you get the issue, just by opening the analysis?
