### ISSUE TITLE
Freq Process - bootstrap + local tests do not work?

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jaspProcess#93]
I just encountered some more issues with the process module when running bootstrap (setting for all models does not seem to affect any of the output?) and local tests (gives error below)
![image](https://github.com/jasp-stats/jaspProcess/assets/15704203/c96174ad-15a7-4061-b9ca-8cfec8cee4f9)

[video_games.zip](https://github.com/jasp-stats/jaspProcess/files/15249333/video_games.zip)

**Comment by JohnnyDoorn** [comment]
The local test bug seems to be a state issue, since after refreshing it does show a more informative error message

**Comment by maltelueken** [comment]
I will look into it!
