### ISSUE TITLE
when plotting and showing both labels and colors as legend, would be nice to have the same order so that one can match color with variable type

### ISSUE THREAD

**Issue by ThijsVroegh** [jasp-stats/jaspProcess#95]
when plotting and showing both labels and colors as legend to the conceptual and statistical path plots, would be nice to have the same order so that one can match color with variable type

![image](https://github.com/jasp-stats/jaspProcess/assets/56916115/127df2cd-fb15-4893-9c28-d15d5247d5ba)

**Comment by maltelueken** [comment]
I don't understand, the order in both plots is the same, right? Which order would you like to be matched?

**Comment by maltelueken** [comment]
Nevermind, I know what you mean, it's just not visible in this plot.
